/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Aluno;
import model.bean.Turma;
import model.dao.AlunoDAO;
import model.dao.TurmaDAO;

/**
 *
 * @author paulo
 */
public class ViewModificarExcluirAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewModificarExcluirAluno
     */
    private final List<Aluno> listAluno = new ArrayList<>();

    public ViewModificarExcluirAluno() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
        tblAlunos.setRowSorter(new TableRowSorter(model));
        readTurmas();
        readTblAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbTurmas = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Modificar ou Remover Aluno(a)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        cmbTurmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos os Alunos" }));
        cmbTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurmasActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTurmas, javax.swing.GroupLayout.Alignment.TRAILING, 0, 157, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela de Alunos"));

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Data Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAlunosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAlunosMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlunosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblAlunosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblAlunosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlunos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setButons(String option) {
        if (option.equals("formExcluirAluno")) {
            btnModificar.setEnabled(false);
        } else if (option.equals("formModificaAluno")) {
            btnRemover.setEnabled(false);
        }

    }

    private void cmbTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurmasActionPerformed
        // TODO add your handling code here:
        //System.out.println("" + cmbTurmas.getSelectedItem().toString());
        readTblAlunos();
    }//GEN-LAST:event_cmbTurmasActionPerformed

    private void tblAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
            ViewFormularioAluno formAluno = new ViewFormularioAluno();
            formAluno.fillTheForm(listAluno.get(tblAlunos.getSelectedRow()));
            ViewTelaPrincipal.dskTeleInicial.add(formAluno);
            formAluno.setVisible(true);
            formAluno.setPosition();
//            System.out.println("Linha selecionada: " + tblAlunos.getSelectedRow());
//            System.out.println("Clique simples");
        }
    }//GEN-LAST:event_tblAlunosMouseClicked

    private void tblAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlunosMouseEntered

    private void tblAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlunosMouseExited

    private void tblAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlunosMousePressed

    private void tblAlunosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlunosMouseReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (tblAlunos.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
            ViewFormularioAluno formAluno = new ViewFormularioAluno();
            formAluno.fillTheForm(listAluno.get(tblAlunos.getSelectedRow()));
            ViewTelaPrincipal.dskTeleInicial.add(formAluno);
            formAluno.setVisible(true);
            formAluno.setPosition();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Aluno para modificar!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (tblAlunos.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
            int row = tblAlunos.getSelectedRow();
            AlunoDAO alunoDAO = new AlunoDAO();
            TurmaDAO turmaDAO = new TurmaDAO();
            Aluno aluno = new Aluno();
            aluno = listAluno.get(row);
            //System.out.println("Nome: " + aluno.getNome());
            //aluno.setTurmasMatriculadas(turmaDAO.readTurmasAluno(aluno));
            //System.out.println("Nome da Turma: " + aluno.getTurmasMatriculadas().get(0).getNome());
            if (turmaDAO.readTurmasAluno(aluno) == null) {
                alunoDAO.delete(aluno);
                model.removeRow(row);
            } else {
                alunoDAO.deleteAlunoTurmas(aluno);
                model.removeRow(row);
            }

//            if (cmbTurmas.getSelectedItem().toString().equals("Todos os Alunos"))
//                alunoDAO.delete(listAluno.get(row));
//
//                Turma turma = new Turma();
//                turma = (Turma) cmbTurmas.getSelectedItem();
//                alunoDAO.deleteAlunoTurma(listAluno.get(row), turma);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Aluno para excluir!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void readTblAlunos() {
        DefaultTableModel model = (DefaultTableModel) tblAlunos.getModel();
        model.setNumRows(0);
        AlunoDAO alunoDAO = new AlunoDAO();
        listAluno.clear();
        if (cmbTurmas.getSelectedItem().toString().equals("Todos os Alunos")) {
            alunoDAO.read().stream().forEach((aluno) -> {
                listAluno.add(aluno);
                model.addRow(new Object[]{
                    aluno.getCpf(),
                    aluno.getNome(),
                    aluno.getDataNascimento()
                });
            });
        } else {
            Turma turma = new Turma();
            turma = (Turma) cmbTurmas.getSelectedItem();

            alunoDAO.readAlunosTurma(turma).stream().forEach((aluno) -> {
                listAluno.add(aluno);
                model.addRow(new Object[]{
                    aluno.getCpf(),
                    aluno.getNome(),
                    aluno.getDataNascimento()
                });
            });
        }
    }

    private void readTurmas() {
        TurmaDAO turmaDAO = new TurmaDAO();
        turmaDAO.read().stream().forEach((turma) -> {
            cmbTurmas.addItem(turma);
        });
    }

    public void setPosition() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<Object> cmbTurmas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlunos;
    // End of variables declaration//GEN-END:variables
}
