/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author paulo
 */
public class ViewTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewTelaPrincipal
     */
    public ViewTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskTeleInicial = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAluno = new javax.swing.JMenu();
        jMenuAdicionarAluno = new javax.swing.JMenuItem();
        jMenuModificarAluno = new javax.swing.JMenuItem();
        jMenuRemoverAluno = new javax.swing.JMenuItem();
        jMenuProfessor = new javax.swing.JMenu();
        jMenuAdicionarProfessor = new javax.swing.JMenuItem();
        jMenuModificarProfessor = new javax.swing.JMenuItem();
        jMenuRemoverProfessor = new javax.swing.JMenuItem();
        jMenuCurso = new javax.swing.JMenu();
        jMenuAdicionarCurso = new javax.swing.JMenuItem();
        jMenuModificarCurso = new javax.swing.JMenuItem();
        jMenuRemoverCurso = new javax.swing.JMenuItem();
        jMenuTurma = new javax.swing.JMenu();
        jMenuAdicionarTurma = new javax.swing.JMenuItem();
        jMenuModificarTurma = new javax.swing.JMenuItem();
        jMenuRemoverTurma = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuMatricula = new javax.swing.JMenu();
        jMenuEfetuar = new javax.swing.JMenuItem();
        jMenuCancelar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CursosSIC");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/folder_wrench.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/door_out.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/group.png"))); // NOI18N
        jMenu2.setText("Cadastros");

        jMenuAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user.png"))); // NOI18N
        jMenuAluno.setText("Alunos");

        jMenuAdicionarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user_add.png"))); // NOI18N
        jMenuAdicionarAluno.setText("Adicionar");
        jMenuAdicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarAlunoActionPerformed(evt);
            }
        });
        jMenuAluno.add(jMenuAdicionarAluno);

        jMenuModificarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user_edit.png"))); // NOI18N
        jMenuModificarAluno.setText("Modificar");
        jMenuModificarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarAlunoActionPerformed(evt);
            }
        });
        jMenuAluno.add(jMenuModificarAluno);

        jMenuRemoverAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user_delete.png"))); // NOI18N
        jMenuRemoverAluno.setText("Remover");
        jMenuRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRemoverAlunoActionPerformed(evt);
            }
        });
        jMenuAluno.add(jMenuRemoverAluno);

        jMenu2.add(jMenuAluno);

        jMenuProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user_suit.png"))); // NOI18N
        jMenuProfessor.setText("Professores");

        jMenuAdicionarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/application_add.png"))); // NOI18N
        jMenuAdicionarProfessor.setText("Adicionar");
        jMenuAdicionarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarProfessorActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuAdicionarProfessor);

        jMenuModificarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/application_edit.png"))); // NOI18N
        jMenuModificarProfessor.setText("Modificar");
        jMenuProfessor.add(jMenuModificarProfessor);

        jMenuRemoverProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/application_delete.png"))); // NOI18N
        jMenuRemoverProfessor.setText("Remover");
        jMenuProfessor.add(jMenuRemoverProfessor);

        jMenu2.add(jMenuProfessor);

        jMenuCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/report.png"))); // NOI18N
        jMenuCurso.setText("Cursos");

        jMenuAdicionarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/report_add.png"))); // NOI18N
        jMenuAdicionarCurso.setText("Adicionar");
        jMenuAdicionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarCursoActionPerformed(evt);
            }
        });
        jMenuCurso.add(jMenuAdicionarCurso);

        jMenuModificarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/report_edit.png"))); // NOI18N
        jMenuModificarCurso.setText("Modificar");
        jMenuCurso.add(jMenuModificarCurso);

        jMenuRemoverCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/report_delete.png"))); // NOI18N
        jMenuRemoverCurso.setText("Remover");
        jMenuCurso.add(jMenuRemoverCurso);

        jMenu2.add(jMenuCurso);

        jMenuTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/group.png"))); // NOI18N
        jMenuTurma.setText("Turma");

        jMenuAdicionarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/group_add.png"))); // NOI18N
        jMenuAdicionarTurma.setText("Adicionar");
        jMenuAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarTurmaActionPerformed(evt);
            }
        });
        jMenuTurma.add(jMenuAdicionarTurma);

        jMenuModificarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/group_edit.png"))); // NOI18N
        jMenuModificarTurma.setText("Modificar");
        jMenuTurma.add(jMenuModificarTurma);

        jMenuRemoverTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/group_delete.png"))); // NOI18N
        jMenuRemoverTurma.setText("Remover");
        jMenuTurma.add(jMenuRemoverTurma);

        jMenu2.add(jMenuTurma);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/wrench.png"))); // NOI18N
        jMenu3.setText("Ferramentas");

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/magnifier.png"))); // NOI18N
        jMenu5.setText("Pesquisas");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/magnifier_zoom_in.png"))); // NOI18N
        jMenuItem6.setText("Pesquisas");
        jMenu5.add(jMenuItem6);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenuMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user_go.png"))); // NOI18N
        jMenuMatricula.setText("Matrícula");

        jMenuEfetuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/add.png"))); // NOI18N
        jMenuEfetuar.setText("Efetuar");
        jMenuEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEfetuarActionPerformed(evt);
            }
        });
        jMenuMatricula.add(jMenuEfetuar);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/cancel.png"))); // NOI18N
        jMenuCancelar.setText("Calcelar");
        jMenuMatricula.add(jMenuCancelar);

        jMenuBar1.add(jMenuMatricula);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/comments.png"))); // NOI18N
        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskTeleInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskTeleInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarAlunoActionPerformed
        // TODO add your handling code here:
        ViewFormularioAluno formAluno = new ViewFormularioAluno();
        dskTeleInicial.add(formAluno);
        formAluno.setButons("formCadastrarAluno");
        formAluno.setVisible(true);
        formAluno.setPosition();
    }//GEN-LAST:event_jMenuAdicionarAlunoActionPerformed

    private void jMenuAdicionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarCursoActionPerformed
        // TODO add your handling code here:
        ViewFormularioCurso formCurso = new ViewFormularioCurso();
        dskTeleInicial.add(formCurso);
        formCurso.setVisible(true);
        formCurso.setPosition();
    }//GEN-LAST:event_jMenuAdicionarCursoActionPerformed

    private void jMenuAdicionarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarProfessorActionPerformed
        // TODO add your handling code here:
        ViewFormularioProfessor formProfessor = new ViewFormularioProfessor();
        dskTeleInicial.add(formProfessor);
        formProfessor.setVisible(true);
        formProfessor.setPosition();
    }//GEN-LAST:event_jMenuAdicionarProfessorActionPerformed

    private void jMenuAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarTurmaActionPerformed
        // TODO add your handling code here:
        ViewFormularioTurma formTurma = new ViewFormularioTurma();
        dskTeleInicial.add(formTurma);
        formTurma.setVisible(true);
        formTurma.setPosition();
    }//GEN-LAST:event_jMenuAdicionarTurmaActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuModificarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarAlunoActionPerformed
        // TODO add your handling code here:
        ViewModificarExcluirAluno formModificaAluno = new ViewModificarExcluirAluno();
        dskTeleInicial.add(formModificaAluno);
        formModificaAluno.setVisible(true);
        formModificaAluno.setPosition();
        formModificaAluno.setButons("formModificaAluno");

    }//GEN-LAST:event_jMenuModificarAlunoActionPerformed

    private void jMenuRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRemoverAlunoActionPerformed
        // TODO add your handling code here:
        ViewModificarExcluirAluno formExcluirAluno = new ViewModificarExcluirAluno();
        dskTeleInicial.add(formExcluirAluno);
        formExcluirAluno.setVisible(true);
        formExcluirAluno.setPosition();
        formExcluirAluno.setButons("formExcluirAluno");
    }//GEN-LAST:event_jMenuRemoverAlunoActionPerformed

    private void jMenuEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEfetuarActionPerformed
        // TODO add your handling code here:
        ViewMaticularAluno formMatriculaAluno = new ViewMaticularAluno();
        dskTeleInicial.add(formMatriculaAluno);
        formMatriculaAluno.setVisible(true);
        formMatriculaAluno.setPosition();
    }//GEN-LAST:event_jMenuEfetuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dskTeleInicial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAdicionarAluno;
    private javax.swing.JMenuItem jMenuAdicionarCurso;
    private javax.swing.JMenuItem jMenuAdicionarProfessor;
    private javax.swing.JMenuItem jMenuAdicionarTurma;
    private javax.swing.JMenu jMenuAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCancelar;
    private javax.swing.JMenu jMenuCurso;
    private javax.swing.JMenuItem jMenuEfetuar;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuMatricula;
    private javax.swing.JMenuItem jMenuModificarAluno;
    private javax.swing.JMenuItem jMenuModificarCurso;
    private javax.swing.JMenuItem jMenuModificarProfessor;
    private javax.swing.JMenuItem jMenuModificarTurma;
    private javax.swing.JMenu jMenuProfessor;
    private javax.swing.JMenuItem jMenuRemoverAluno;
    private javax.swing.JMenuItem jMenuRemoverCurso;
    private javax.swing.JMenuItem jMenuRemoverProfessor;
    private javax.swing.JMenuItem jMenuRemoverTurma;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jMenuTurma;
    // End of variables declaration//GEN-END:variables
}
